name: QIDE AppImage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-appimage:
  
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: install deps
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install g++-11 cmake qt5-default qtbase5-dev qtbase5-dev-tools libzip-dev qtdeclarative5-dev
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 10
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 10
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
          sudo update-alternatives --set cc /usr/bin/gcc
          sudo update-alternatives --set c++ /usr/bin/g++
      
      - name: build AppImage
        run: ./build-appimage.sh

      - uses: actions/upload-artifact@v2
        with:
          path: '*.AppImage'
          
      - name: version
        run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
        id: version

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: dev
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - uses: softprops/action-gh-release@v1
        with:
          files: '*.AppImage'
