name: QIDE CI

on:
  push:
    branches:
      - main
      - master
  
    tags-ignore:
      - "v*.*.*"
      - "autobuild"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: install deps
        run: |
          sudo apt update
          sudo apt install g++ cmake qt5-default qtbase5-dev qtbase5-dev-tools libzip-dev qtdeclarative5-dev
      
      - name: build project
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build . -- -j$(nproc)
